#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

//#define COMMUNICATION_ENABLED
#define REMOTE_CONTROL_ENABLED
//#define DEBUGGING_ENABLED
#define USING_DISPLAY

#define AUTOMATED_DRIVING_ENABLED

#endif




/* SPEED LEVELS 0...255 */
#define SPEED_HALT 0
#define SPEED_SLOW 100
#define SPEED_FAST 250