#ifndef CONFIGURATION_H_
#define CONFIGURATION_H_

//#define COMMUNICATION_ENABLED
#define REMOTE_CONTROL_ENABLED
//#define DEBUGGING_ENABLED
#define USING_DISPLAY

#define AUTOMATED_DRIVING_ENABLED

#endif